#!/usr/bin/env python
#!/usr/bin/env python

import argparse
import csv
import json
import math
import time
from collections import defaultdict
from copy import deepcopy
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import matplotlib
matplotlib.use("Agg", force=True)
import matplotlib.pyplot as plt
import numpy as np
import torch
from safetensors.torch import load_file as load_safetensors
from tqdm import tqdm

from configs.epb_3d.config import all_experiments
from src.data import VoxelImage3dEnergyDataset, infer_ionic_conc_from_path
from src.model import MultiScaleConv3dEPBModel

# Force headless rendering so figure export never depends on X11/GUI.
plt.ioff()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Visualize predicted potential maps vs ground truth on eval/test split and "
            "report interpolation/extrapolation metrics by ionic concentration."
        )
    )
    parser.add_argument(
        "--experiment-name",
        type=str,
        required=True,
        help="Experiment key from configs/epb_3d/*, e.g. unet_psz32_ctx48_...",
    )
    parser.add_argument(
        "--model-ckpt-path",
        type=str,
        required=True,
        help="Path to model checkpoint (.safetensors / .pt / .pth) or model directory.",
    )
    parser.add_argument(
        "--data-split-json-path",
        type=str,
        required=True,
        help="Path to data_split.json generated by training.",
    )
    parser.add_argument(
        "--split",
        type=str,
        choices=["train", "eval", "test"],
        default="test",
        help="Which split in data_split.json to visualize/evaluate.",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        required=True,
        help="Output folder for figures and metrics.",
    )
    parser.add_argument(
        "--max-samples",
        type=int,
        default=32,
        help="Maximum number of samples from selected split (after --conc filtering).",
    )
    parser.add_argument(
        "--start-index",
        type=int,
        default=0,
        help="Starting index in selected split (after --conc filtering).",
    )
    parser.add_argument(
        "--patch-size",
        type=int,
        default=None,
        help="Optional override for trainer/model patch size.",
    )
    parser.add_argument(
        "--mapper-version",
        type=str,
        choices=["u-shape", "u-net", "resnet", "fno"],
        default=None,
        help="Optional override for energy-model.reaction-field-mapping-version.",
    )
    parser.add_argument(
        "--use-ionic-conc",
        action="store_true",
        help="Enable ionic concentration conditioning for visualization run.",
    )
    parser.add_argument(
        "--no-use-ionic-conc",
        action="store_true",
        help="Disable ionic concentration conditioning for visualization run.",
    )
    parser.add_argument(
        "--ionic-conditioning",
        type=str,
        choices=["add", "film"],
        default=None,
        help=(
            "Ionic conditioning mode for checkpoint compatibility. "
            "Set to 'film' for FiLM-conditioned ionic concentration models."
        ),
    )
    parser.add_argument(
        "--potential-map-use-atom-mask",
        action="store_true",
        help="Evaluate map metrics only where atom_mask > 0.",
    )
    parser.add_argument(
        "--slice-mode",
        type=str,
        choices=["center", "max-mask"],
        default="center",
        help="Slice selection strategy for 2D visualizations.",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cuda",
        help="Device to run inference on: cuda / cpu / cuda:0 ...",
    )
    parser.add_argument(
        "--save-npz",
        action="store_true",
        help="Save raw pred/true/mask 3D arrays per sample as compressed npz.",
    )
    parser.add_argument(
        "--no-figures",
        action="store_true",
        help="Skip figure generation and only save metrics/csv outputs.",
    )
    parser.add_argument(
        "--measure-inference-time",
        action="store_true",
        help="Measure per-sample model forward latency and pipeline runtime.",
    )
    parser.add_argument(
        "--timing-warmup-samples",
        type=int,
        default=10,
        help="Number of initial samples to exclude from steady-state timing stats.",
    )

    # ---- Ionic concentration sample filtering -----------------------------
    # These flags filter `split_paths` *before* --start-index / --max-samples
    # slicing. The train split used for interp/extrap classification is not
    # filtered, so the interpolation/extrapolation tags stay honest.
    parser.add_argument(
        "--conc",
        type=float,
        action="append",
        default=None,
        metavar="C",
        help=(
            "Keep only samples whose inferred ionic concentration equals one of "
            "these values (mol/L). Repeatable: --conc 0.0 --conc 0.15. "
            "Combined with --conc-min/--conc-max via set union."
        ),
    )
    parser.add_argument(
        "--conc-min",
        type=float,
        default=None,
        help="Keep samples with inferred conc >= this (mol/L).",
    )
    parser.add_argument(
        "--conc-max",
        type=float,
        default=None,
        help="Keep samples with inferred conc <= this (mol/L).",
    )
    parser.add_argument(
        "--conc-exclude",
        type=float,
        action="append",
        default=None,
        metavar="C",
        help="Drop samples whose inferred conc matches one of these (applied last).",
    )
    parser.add_argument(
        "--conc-tol",
        type=float,
        default=1e-6,
        help="Float tolerance for --conc / --conc-exclude equality tests.",
    )
    return parser.parse_args()


def resolve_checkpoint_path(path: str) -> Path:
    p = Path(path)
    if p.is_file():
        return p
    if not p.exists():
        raise FileNotFoundError(f"Checkpoint path not found: {path}")

    candidates = [
        p / "model.safetensors",
        p / "pytorch_model.bin",
        p / "pytorch_model.pt",
        p / "model.pt",
        p / "model.pth",
    ]
    for c in candidates:
        if c.exists():
            return c
    raise FileNotFoundError(
        "Could not resolve model file from directory. Tried: "
        + ", ".join(str(c) for c in candidates)
    )


def load_state_dict(checkpoint_file: Path) -> Dict[str, torch.Tensor]:
    suffix = checkpoint_file.suffix.lower()
    if suffix == ".safetensors":
        return load_safetensors(str(checkpoint_file), device="cpu")

    loaded = torch.load(checkpoint_file, map_location="cpu")
    if isinstance(loaded, dict):
        if all(torch.is_tensor(v) for v in loaded.values()):
            return loaded
        if "model" in loaded and isinstance(loaded["model"], dict):
            return loaded["model"]
        if "state_dict" in loaded and isinstance(loaded["state_dict"], dict):
            return loaded["state_dict"]
    raise ValueError(f"Unsupported checkpoint format: {checkpoint_file}")


def choose_slice(mask_3d: np.ndarray, axis: int, mode: str) -> int:
    if mode == "center":
        return mask_3d.shape[axis] // 2

    if axis == 0:
        score = mask_3d.sum(axis=(1, 2))
    elif axis == 1:
        score = mask_3d.sum(axis=(0, 2))
    else:
        score = mask_3d.sum(axis=(0, 1))
    return int(np.argmax(score))


def plot_triplet(
    pred_3d: np.ndarray,
    true_3d: np.ndarray,
    eval_mask_3d: np.ndarray,
    out_png: Path,
    title: str,
    slice_mode: str,
) -> None:
    pred = pred_3d.copy()
    true = true_3d.copy()
    err = pred - true

    valid_pred = pred[eval_mask_3d]
    valid_true = true[eval_mask_3d]
    valid_err = err[eval_mask_3d]

    if valid_pred.size == 0:
        vmax = 1.0
        emax = 1.0
    else:
        vmax = np.percentile(
            np.abs(np.concatenate([valid_pred.ravel(), valid_true.ravel()])), 99
        )
        emax = np.percentile(np.abs(valid_err.ravel()), 99)
        vmax = max(vmax, 1e-8)
        emax = max(emax, 1e-8)

    z = choose_slice(eval_mask_3d, axis=0, mode=slice_mode)
    y = choose_slice(eval_mask_3d, axis=1, mode=slice_mode)
    x = choose_slice(eval_mask_3d, axis=2, mode=slice_mode)

    views = [
        ("XY", pred[z], true[z], err[z]),
        ("XZ", pred[:, y, :], true[:, y, :], err[:, y, :]),
        ("YZ", pred[:, :, x], true[:, :, x], err[:, :, x]),
    ]

    fig, axes = plt.subplots(3, 3, figsize=(11, 11))
    for ridx, (name, pred_2d, true_2d, err_2d) in enumerate(views):
        axes[ridx, 0].imshow(pred_2d, cmap="RdBu_r", vmin=-vmax, vmax=vmax)
        axes[ridx, 0].set_title(f"{name} Pred")
        axes[ridx, 1].imshow(true_2d, cmap="RdBu_r", vmin=-vmax, vmax=vmax)
        axes[ridx, 1].set_title(f"{name} GT")
        axes[ridx, 2].imshow(err_2d, cmap="RdBu_r", vmin=-emax, vmax=emax)
        axes[ridx, 2].set_title(f"{name} Err")
        for c in range(3):
            axes[ridx, c].axis("off")

    fig.suptitle(title)
    fig.tight_layout()
    out_png.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_png, dpi=180)
    plt.close(fig)


class MetricAccumulator:
    def __init__(self):
        self.abs_err_sum = 0.0
        self.sq_err_sum = 0.0
        self.ape_sum = 0.0
        self.abs_true_sum = 0.0
        self.y_sum = 0.0
        self.y_sq_sum = 0.0
        self.n = 0.0
        self.sample_count = 0

    def update(self, pred: np.ndarray, true: np.ndarray, mape_eps: float = 1e-6):
        if pred.size == 0:
            return
        diff = pred - true
        abs_err = np.abs(diff)
        self.abs_err_sum += float(abs_err.sum())
        self.sq_err_sum += float(np.square(diff).sum())
        self.ape_sum += float((abs_err / np.maximum(np.abs(true), mape_eps)).sum())
        self.abs_true_sum += float(np.abs(true).sum())
        self.y_sum += float(true.sum())
        self.y_sq_sum += float(np.square(true).sum())
        self.n += float(true.size)
        self.sample_count += 1

    def finalize(self) -> Dict[str, float]:
        if self.n == 0:
            return {
                "sample_count": 0,
                "n_voxels": 0,
                "mae": float("nan"),
                "rmse": float("nan"),
                "mape": float("nan"),
                "wape": float("nan"),
                "r2": float("nan"),
            }

        mae = self.abs_err_sum / self.n
        rmse = math.sqrt(self.sq_err_sum / self.n)
        mape = self.ape_sum / self.n
        wape = (
            float("nan")
            if self.abs_true_sum <= 1e-12
            else self.abs_err_sum / self.abs_true_sum
        )
        ss_tot = self.y_sq_sum - (self.y_sum * self.y_sum) / self.n
        if ss_tot <= 1e-12:
            r2 = float("nan")
        else:
            r2 = 1.0 - self.sq_err_sum / ss_tot
        return {
            "sample_count": self.sample_count,
            "n_voxels": int(self.n),
            "mae": mae,
            "rmse": rmse,
            "mape": mape,
            "wape": wape,
            "r2": r2,
        }


def maybe_extract_train_conc_range(
    split_json: dict, train_min_override: Optional[float], train_max_override: Optional[float]
) -> Optional[Tuple[float, float]]:
    if train_min_override is not None and train_max_override is not None:
        return (train_min_override, train_max_override)

    train_files = split_json.get("splits", {}).get("train", [])
    if len(train_files) == 0:
        return None

    concs = [infer_ionic_conc_from_path(p) for p in train_files]
    if len(concs) == 0:
        return None

    return (float(np.min(concs)), float(np.max(concs)))


def classify_interp_extrap(conc: float, train_range: Optional[Tuple[float, float]]) -> str:
    if train_range is None:
        return "unknown"
    cmin, cmax = train_range
    return "interpolation" if cmin <= conc <= cmax else "extrapolation"


def summarize_latency_ms(values: List[float]) -> Dict[str, float]:
    if len(values) == 0:
        return {
            "count": 0,
            "mean_ms": float("nan"),
            "std_ms": float("nan"),
            "min_ms": float("nan"),
            "p50_ms": float("nan"),
            "p90_ms": float("nan"),
            "p95_ms": float("nan"),
            "p99_ms": float("nan"),
            "max_ms": float("nan"),
            "throughput_samples_per_sec": float("nan"),
        }

    arr = np.asarray(values, dtype=np.float64)
    mean_ms = float(arr.mean())
    return {
        "count": int(arr.size),
        "mean_ms": mean_ms,
        "std_ms": float(arr.std()),
        "min_ms": float(arr.min()),
        "p50_ms": float(np.percentile(arr, 50)),
        "p90_ms": float(np.percentile(arr, 90)),
        "p95_ms": float(np.percentile(arr, 95)),
        "p99_ms": float(np.percentile(arr, 99)),
        "max_ms": float(arr.max()),
        "throughput_samples_per_sec": float("nan") if mean_ms <= 1e-12 else 1000.0 / mean_ms,
    }


def build_conc_filter(args: argparse.Namespace):
    """Return (is_active, predicate) for ionic-conc sample filtering.

    Include semantics:
      - --conc        value-set include  (OR across listed values)
      - --conc-min/max range include     (AND across bounds)
      - If both value and range includes are set: their union is allowed.
      - If neither is set: nothing is excluded on the include side.
    Exclude semantics:
      - --conc-exclude  hard drop, applied after include filters.
    """
    is_active = (
        args.conc is not None
        or args.conc_min is not None
        or args.conc_max is not None
        or args.conc_exclude is not None
    )
    tol = args.conc_tol

    def predicate(conc: float) -> bool:
        value_ok: Optional[bool] = None
        if args.conc is not None:
            value_ok = any(abs(conc - v) <= tol for v in args.conc)

        range_ok: Optional[bool] = None
        if args.conc_min is not None or args.conc_max is not None:
            range_ok = True
            if args.conc_min is not None and conc < args.conc_min - tol:
                range_ok = False
            if args.conc_max is not None and conc > args.conc_max + tol:
                range_ok = False

        if value_ok is None and range_ok is None:
            allow = True
        elif value_ok is None:
            allow = bool(range_ok)
        elif range_ok is None:
            allow = bool(value_ok)
        else:
            allow = bool(value_ok or range_ok)

        if allow and args.conc_exclude:
            if any(abs(conc - v) <= tol for v in args.conc_exclude):
                allow = False
        return allow

    return is_active, predicate


def main():
    args = parse_args()
    run_t0 = time.perf_counter()

    if args.use_ionic_conc and args.no_use_ionic_conc:
        raise ValueError("Cannot set both --use-ionic-conc and --no-use-ionic-conc.")
    if args.no_use_ionic_conc and args.ionic_conditioning is not None:
        raise ValueError(
            "Cannot set --ionic-conditioning when --no-use-ionic-conc is enabled."
        )

    if args.experiment_name not in all_experiments:
        raise KeyError(
            f"Unknown experiment '{args.experiment_name}'. "
            f"Available: {sorted(all_experiments.keys())[:10]} ..."
        )

    exp = deepcopy(all_experiments[args.experiment_name])
    if exp.model_cls != "voxel_based":
        raise ValueError(
            f"This script currently supports voxel_based model only, got {exp.model_cls}."
        )

    if args.patch_size is not None:
        exp.trainer.patch_size = args.patch_size
        exp.energy_model.patch_size = args.patch_size
    if args.mapper_version is not None:
        exp.energy_model.reaction_field_mapping_version = args.mapper_version
    if args.use_ionic_conc:
        exp.energy_model.use_ionic_conc = True
    if args.no_use_ionic_conc:
        exp.energy_model.use_ionic_conc = False
    if args.ionic_conditioning is not None:
        exp.energy_model.ionic_conditioning = args.ionic_conditioning
        if not args.no_use_ionic_conc:
            exp.energy_model.use_ionic_conc = True

    split_json_path = Path(args.data_split_json_path)
    with open(split_json_path, "r") as f:
        split_json = json.load(f)

    split_paths = split_json["splits"][args.split]
    if len(split_paths) == 0:
        raise ValueError(f"No files in split '{args.split}'.")

    # --- Optional ionic-concentration filtering (before slicing) -----------
    conc_filter_active, conc_allowed = build_conc_filter(args)
    if conc_filter_active:
        n_before = len(split_paths)
        split_paths = [
            p for p in split_paths if conc_allowed(infer_ionic_conc_from_path(p))
        ]
        kept_concs = sorted({infer_ionic_conc_from_path(p) for p in split_paths})
        print(
            f"Conc filter: {n_before} -> {len(split_paths)} paths "
            f"(kept concs: {[f'{c:.4f}' for c in kept_concs]})"
        )
        if len(split_paths) == 0:
            raise ValueError("No paths remain after --conc filter.")

    start = max(args.start_index, 0)
    end = min(len(split_paths), start + args.max_samples)
    selected_paths = split_paths[start:end]

    output_dir = Path(args.output_dir)
    figure_dir = output_dir / "figures"
    raw_npz_dir = output_dir / "raw_npz"
    output_dir.mkdir(parents=True, exist_ok=True)
    if not args.no_figures:
        figure_dir.mkdir(parents=True, exist_ok=True)
    if args.save_npz:
        raw_npz_dir.mkdir(parents=True, exist_ok=True)

    model = MultiScaleConv3dEPBModel(exp.energy_model)
    ckpt_path = resolve_checkpoint_path(args.model_ckpt_path)
    model.load_state_dict(load_state_dict(ckpt_path))

    use_cuda = str(args.device).startswith("cuda")
    if use_cuda and not torch.cuda.is_available():
        print("CUDA requested but unavailable; falling back to CPU.")
        device = torch.device("cpu")
    else:
        device = torch.device(args.device)

    model = model.to(device).eval()

    dataset = VoxelImage3dEnergyDataset(
        selected_paths,
        patch_size=exp.trainer.patch_size,
        epb_mean=exp.trainer.epb_mean,
        epb_std=exp.trainer.epb_std,
        do_random_crop=False,
    )

    train_conc_range = maybe_extract_train_conc_range(split_json, None, None)
    if train_conc_range is not None:
        print(
            f"Train ionic concentration range inferred from paths: "
            f"[{train_conc_range[0]:.6f}, {train_conc_range[1]:.6f}]"
        )
    else:
        print("Could not infer train ionic concentration range; interp/extrap set to unknown.")

    global_metrics = MetricAccumulator()
    interp_metrics = MetricAccumulator()
    extra_metrics = MetricAccumulator()
    unknown_metrics = MetricAccumulator()
    per_conc_metrics: Dict[float, MetricAccumulator] = defaultdict(MetricAccumulator)
    rows: List[dict] = []
    timing_warmup = max(args.timing_warmup_samples, 0)
    forward_times_ms_all: List[float] = []
    forward_times_ms_steady: List[float] = []
    sample_times_ms_all: List[float] = []
    sample_times_ms_steady: List[float] = []

    for local_idx in tqdm(range(len(dataset)), desc=f"Visualizing {args.split}"):
        sample_t0 = time.perf_counter() if args.measure_inference_time else 0.0
        (
            level_set,
            atom_charge,
            atom_type,
            atom_mask,
            potential,
            grid_info,
        ) = dataset[local_idx]

        abs_idx = start + local_idx
        source_path = selected_paths[local_idx]
        ionic_conc = float(grid_info[1]) if np.asarray(grid_info).size > 1 else 0.0
        group = classify_interp_extrap(ionic_conc, train_conc_range)
        infer_forward_ms = float("nan")

        with torch.no_grad():
            level_set_b = level_set.unsqueeze(0).to(device, dtype=torch.float32)
            atom_charge_b = atom_charge.unsqueeze(0).to(device, dtype=torch.float32)
            atom_type_b = atom_type.unsqueeze(0).to(device, dtype=torch.float32)
            atom_mask_b = atom_mask.unsqueeze(0).to(device, dtype=torch.float32)
            grid_info_b = (
                torch.from_numpy(np.asarray(grid_info))
                .to(device, dtype=torch.float32)
                .unsqueeze(0)
            )
            if args.measure_inference_time and device.type == "cuda":
                torch.cuda.synchronize(device)
            infer_t0 = time.perf_counter() if args.measure_inference_time else 0.0
            _, pred_map = model(
                level_set_b,
                atom_charge_b,
                atom_type_b,
                atom_mask_b,
                grid_info_b,
                return_per_epb=True,
            )
            if args.measure_inference_time:
                if device.type == "cuda":
                    torch.cuda.synchronize(device)
                infer_forward_ms = (time.perf_counter() - infer_t0) * 1000.0
                forward_times_ms_all.append(infer_forward_ms)
                if local_idx >= timing_warmup:
                    forward_times_ms_steady.append(infer_forward_ms)

        pred_3d = pred_map[0, 0].detach().cpu().numpy()
        true_3d = potential[0].detach().cpu().numpy()
        atom_mask_3d = atom_mask[0].detach().cpu().numpy() > 0

        finite_mask_3d = np.isfinite(true_3d)
        if args.potential_map_use_atom_mask:
            eval_mask_3d = atom_mask_3d & finite_mask_3d
        else:
            eval_mask_3d = finite_mask_3d

        pred_valid = pred_3d[eval_mask_3d]
        true_valid = true_3d[eval_mask_3d]

        if true_valid.size == 0:
            mae = float("nan")
            rmse = float("nan")
            mape = float("nan")
            wape = float("nan")
            r2 = float("nan")
        else:
            diff = pred_valid - true_valid
            mae = float(np.mean(np.abs(diff)))
            rmse = float(np.sqrt(np.mean(np.square(diff))))
            mape = float(np.mean(np.abs(diff) / np.maximum(np.abs(true_valid), 1e-6)))
            abs_true_sum = float(np.sum(np.abs(true_valid)))
            wape = (
                float("nan")
                if abs_true_sum <= 1e-12
                else float(np.sum(np.abs(diff))) / abs_true_sum
            )
            ss_tot = float(np.sum(np.square(true_valid - np.mean(true_valid))))
            r2 = float("nan") if ss_tot <= 1e-12 else 1.0 - float(np.sum(np.square(diff))) / ss_tot

        global_metrics.update(pred_valid, true_valid)
        per_conc_metrics[ionic_conc].update(pred_valid, true_valid)
        if group == "interpolation":
            interp_metrics.update(pred_valid, true_valid)
        elif group == "extrapolation":
            extra_metrics.update(pred_valid, true_valid)
        else:
            unknown_metrics.update(pred_valid, true_valid)

        fig_path = ""
        if not args.no_figures:
            fig_name = f"{abs_idx:05d}_{Path(source_path).stem}.png"
            fig_path = str(figure_dir / fig_name)
            plot_triplet(
                pred_3d=pred_3d,
                true_3d=true_3d,
                eval_mask_3d=eval_mask_3d,
                out_png=figure_dir / fig_name,
                title=f"idx={abs_idx} | conc={ionic_conc:.4f} | {group}",
                slice_mode=args.slice_mode,
            )

        if args.save_npz:
            np.savez_compressed(
                raw_npz_dir / f"{abs_idx:05d}_{Path(source_path).stem}.npz",
                pred=pred_3d.astype(np.float32),
                true=true_3d.astype(np.float32),
                eval_mask=eval_mask_3d.astype(np.uint8),
                atom_mask=atom_mask_3d.astype(np.uint8),
                ionic_conc=np.array([ionic_conc], dtype=np.float32),
            )

        rows.append(
            {
                "idx": abs_idx,
                "path": source_path,
                "ionic_conc": ionic_conc,
                "group": group,
                "n_eval_voxels": int(true_valid.size),
                "mae": mae,
                "rmse": rmse,
                "mape": mape,
                "wape": wape,
                "r2": r2,
                "inference_forward_ms": infer_forward_ms,
                "sample_pipeline_ms": float("nan"),
                "figure": fig_path,
            }
        )
        if args.measure_inference_time:
            sample_ms = (time.perf_counter() - sample_t0) * 1000.0
            rows[-1]["sample_pipeline_ms"] = sample_ms
            sample_times_ms_all.append(sample_ms)
            if local_idx >= timing_warmup:
                sample_times_ms_steady.append(sample_ms)

    # --- Per-concentration breakdown ---
    per_conc_finalized = {}
    for conc in sorted(per_conc_metrics.keys()):
        group = classify_interp_extrap(conc, train_conc_range)
        result = per_conc_metrics[conc].finalize()
        result["group"] = group
        per_conc_finalized[f"{conc:.4f}"] = result

    metrics_summary = {
        "experiment_name": args.experiment_name,
        "checkpoint": str(ckpt_path),
        "split": args.split,
        "num_selected_samples": len(selected_paths),
        "train_conc_range_from_paths": train_conc_range,
        "conc_filter": {
            "active": conc_filter_active,
            "conc": args.conc,
            "conc_min": args.conc_min,
            "conc_max": args.conc_max,
            "conc_exclude": args.conc_exclude,
            "conc_tol": args.conc_tol,
        },
        "global": global_metrics.finalize(),
        "interpolation": interp_metrics.finalize(),
        "extrapolation": extra_metrics.finalize(),
        "unknown": unknown_metrics.finalize(),
        "per_concentration": per_conc_finalized,
    }
    if args.measure_inference_time:
        metrics_summary["timing"] = {
            "device": str(device),
            "warmup_samples_excluded_for_steady_stats": timing_warmup,
            "forward_latency_ms_all": summarize_latency_ms(forward_times_ms_all),
            "forward_latency_ms_steady": summarize_latency_ms(forward_times_ms_steady),
            "sample_pipeline_ms_all": summarize_latency_ms(sample_times_ms_all),
            "sample_pipeline_ms_steady": summarize_latency_ms(sample_times_ms_steady),
            "total_runtime_seconds": float(time.perf_counter() - run_t0),
        }

    with open(output_dir / "metrics_summary.json", "w") as f:
        json.dump(metrics_summary, f, indent=2)

    with open(output_dir / "sample_metrics.csv", "w", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "idx",
                "path",
                "ionic_conc",
                "group",
                "n_eval_voxels",
                "mae",
                "rmse",
                "mape",
                "wape",
                "r2",
                "inference_forward_ms",
                "sample_pipeline_ms",
                "figure",
            ],
        )
        writer.writeheader()
        for row in rows:
            writer.writerow(row)

    # --- Write per-concentration CSV ---
    conc_csv_path = output_dir / "per_concentration_metrics.csv"
    with open(conc_csv_path, "w", newline="") as f:
        conc_fields = [
            "ionic_conc",
            "group",
            "sample_count",
            "n_voxels",
            "mae",
            "rmse",
            "mape",
            "wape",
            "r2",
        ]
        writer = csv.DictWriter(f, fieldnames=conc_fields)
        writer.writeheader()
        for conc_key, conc_result in per_conc_finalized.items():
            writer.writerow(
                {
                    "ionic_conc": conc_key,
                    "group": conc_result["group"],
                    "sample_count": conc_result["sample_count"],
                    "n_voxels": conc_result["n_voxels"],
                    "mae": conc_result["mae"],
                    "rmse": conc_result["rmse"],
                    "mape": conc_result["mape"],
                    "wape": conc_result["wape"],
                    "r2": conc_result["r2"],
                }
            )

    # --- Print per-concentration table to console ---
    print("\n" + "=" * 95)
    print("Per-concentration breakdown:")
    print("=" * 95)
    header = f"{'Conc':>8s}  {'Group':>14s}  {'#Samples':>8s}  {'MAE':>10s}  {'RMSE':>10s}  {'MAPE':>10s}  {'WAPE':>10s}  {'R²':>8s}"
    print(header)
    print("-" * 95)
    for conc_key, conc_result in per_conc_finalized.items():
        print(
            f"{conc_key:>8s}  {conc_result['group']:>14s}  "
            f"{conc_result['sample_count']:>8d}  "
            f"{conc_result['mae']:>10.4f}  "
            f"{conc_result['rmse']:>10.4f}  "
            f"{conc_result['mape']:>10.4f}  "
            f"{conc_result['wape']:>10.4f}  "
            f"{conc_result['r2']:>8.4f}"
        )
    print("=" * 95)

    print("\nSaved outputs:")
    print(f"- summary: {output_dir / 'metrics_summary.json'}")
    print(f"- per-sample metrics: {output_dir / 'sample_metrics.csv'}")
    print(f"- per-concentration metrics: {conc_csv_path}")
    if args.no_figures:
        print("- figures: skipped (--no-figures)")
    else:
        print(f"- figures: {figure_dir}")
    if args.save_npz:
        print(f"- raw arrays: {raw_npz_dir}")
    if args.measure_inference_time:
        timing = metrics_summary["timing"]
        print("\nTiming summary:")
        print(
            f"- forward latency mean (steady): "
            f"{timing['forward_latency_ms_steady']['mean_ms']:.3f} ms "
            f"(p50={timing['forward_latency_ms_steady']['p50_ms']:.3f}, "
            f"p95={timing['forward_latency_ms_steady']['p95_ms']:.3f})"
        )
        print(
            f"- sample pipeline mean (steady): "
            f"{timing['sample_pipeline_ms_steady']['mean_ms']:.3f} ms "
            f"(p50={timing['sample_pipeline_ms_steady']['p50_ms']:.3f}, "
            f"p95={timing['sample_pipeline_ms_steady']['p95_ms']:.3f})"
        )
        print(
            f"- throughput from steady forward mean: "
            f"{timing['forward_latency_ms_steady']['throughput_samples_per_sec']:.3f} samples/s"
        )
    print("\nKey metrics:")
    print(json.dumps(metrics_summary, indent=2))


if __name__ == "__main__":
    main()
