#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-/data/server10/pinhao2/ML/Ion_Prediction/pbgnn}"
cd "${PROJECT_ROOT}"

# -----------------------------
# User overrides (export before running if needed)
# -----------------------------
GPU_ID="${GPU_ID:-0}"
WANDB_DISABLED="${WANDB_DISABLED:-true}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-unet_psz32_ctx48_protein_complex_with_lset_fully_coverage_rotation_augmented_medium}"
DATASET_GLOB="${DATASET_GLOB:-/data/server10/pinhao2/ML/Ion_Prediction/alphafold_v6/06_apbs_out_npz/*.npz}"
DATASET_GROUP_PATTERN="${DATASET_GROUP_PATTERN:-.npz}"

# Optional fixed split to ensure all runs compare on identical data partitions.
DATA_SPLIT_JSON_PATH="${DATA_SPLIT_JSON_PATH:-}"
# If true and DATA_SPLIT_JSON_PATH is empty, reuse split JSON generated by the first finished run.
AUTO_REUSE_SPLIT="${AUTO_REUSE_SPLIT:-true}"

TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-2}"
EVAL_BATCH_SIZE="${EVAL_BATCH_SIZE:-2}"
PATCH_SIZE="${PATCH_SIZE:-96}"
SMOOTH_L1_BETA="${SMOOTH_L1_BETA:-0.001}"
BASE_TRAIN_LR="${BASE_TRAIN_LR:-5e-4}"
BASE_FINAL_TRAIN_LR="${BASE_FINAL_TRAIN_LR:-1e-6}"
BASE_TRAIN_STEPS="${BASE_TRAIN_STEPS:-8000}"
MAPPER_VERSION="${MAPPER_VERSION:-u-net}"
RESNET_NGF="${RESNET_NGF:-64}"
RESNET_N_BLOCKS="${RESNET_N_BLOCKS:-6}"
RESNET_USE_DROPOUT="${RESNET_USE_DROPOUT:-false}"
RESNET_DROPOUT_P="${RESNET_DROPOUT_P:-0.1}"
RESNET_PADDING_TYPE="${RESNET_PADDING_TYPE:-reflect}"
USE_IONIC_CONC="${USE_IONIC_CONC:-true}"

# nntool envs
NNTOOL_OUTPUT_PATH="${NNTOOL_OUTPUT_PATH:-${PROJECT_ROOT}/outputs}"
NNTOOL_OUTPUT_PATH_DATE="${NNTOOL_OUTPUT_PATH_DATE:-$(date +%m%d%Y/%H%M%S)}"

# Ablation selection:
#   ABLATIONS=all
#   ABLATIONS=baseline,batch4,lr7e4
ABLATIONS="${ABLATIONS:-all}"
RUN_SET_ID="${RUN_SET_ID:-afdb_pot_ablation_$(date +%Y%m%d_%H%M%S)}"
OUT_ROOT="${NNTOOL_OUTPUT_PATH}/${RUN_SET_ID}"
mkdir -p "${OUT_ROOT}/"{logs,meta,runs}

if ! compgen -G "${DATASET_GLOB}" > /dev/null; then
  echo "[ERR] No files matched DATASET_GLOB=${DATASET_GLOB}"
  exit 1
fi

if [[ -n "${DATA_SPLIT_JSON_PATH}" ]] && [[ ! -f "${DATA_SPLIT_JSON_PATH}" ]]; then
  echo "[ERR] DATA_SPLIT_JSON_PATH does not exist: ${DATA_SPLIT_JSON_PATH}"
  echo "      Use a real path, or unset DATA_SPLIT_JSON_PATH to let the script generate one."
  exit 1
fi

python -V > "${OUT_ROOT}/meta/python_version.txt"
pip freeze > "${OUT_ROOT}/meta/pip_freeze.txt"
git rev-parse HEAD > "${OUT_ROOT}/meta/git_commit.txt" 2>/dev/null || true
git diff > "${OUT_ROOT}/meta/git_diff.patch" 2>/dev/null || true
nvidia-smi > "${OUT_ROOT}/meta/nvidia_smi.txt" 2>/dev/null || true

{
  echo "PROJECT_ROOT=${PROJECT_ROOT}"
  echo "GPU_ID=${GPU_ID}"
  echo "WANDB_DISABLED=${WANDB_DISABLED}"
  echo "EXPERIMENT_NAME=${EXPERIMENT_NAME}"
  echo "RUN_SET_ID=${RUN_SET_ID}"
  echo "DATASET_GLOB=${DATASET_GLOB}"
  echo "DATASET_GROUP_PATTERN=${DATASET_GROUP_PATTERN}"
  echo "DATA_SPLIT_JSON_PATH=${DATA_SPLIT_JSON_PATH}"
  echo "AUTO_REUSE_SPLIT=${AUTO_REUSE_SPLIT}"
  echo "TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE}"
  echo "EVAL_BATCH_SIZE=${EVAL_BATCH_SIZE}"
  echo "PATCH_SIZE=${PATCH_SIZE}"
  echo "SMOOTH_L1_BETA=${SMOOTH_L1_BETA}"
  echo "BASE_TRAIN_LR=${BASE_TRAIN_LR}"
  echo "BASE_FINAL_TRAIN_LR=${BASE_FINAL_TRAIN_LR}"
  echo "BASE_TRAIN_STEPS=${BASE_TRAIN_STEPS}"
  echo "MAPPER_VERSION=${MAPPER_VERSION}"
  echo "RESNET_NGF=${RESNET_NGF}"
  echo "RESNET_N_BLOCKS=${RESNET_N_BLOCKS}"
  echo "RESNET_USE_DROPOUT=${RESNET_USE_DROPOUT}"
  echo "RESNET_DROPOUT_P=${RESNET_DROPOUT_P}"
  echo "RESNET_PADDING_TYPE=${RESNET_PADDING_TYPE}"
  echo "USE_IONIC_CONC=${USE_IONIC_CONC}"
  echo "NNTOOL_OUTPUT_PATH=${NNTOOL_OUTPUT_PATH}"
  echo "NNTOOL_OUTPUT_PATH_DATE=${NNTOOL_OUTPUT_PATH_DATE}"
  echo "ABLATIONS=${ABLATIONS}"
} > "${OUT_ROOT}/meta/run_env.txt"

contains_ablation() {
  local key="$1"
  if [[ "${ABLATIONS}" == "all" ]]; then
    return 0
  fi
  [[ ",${ABLATIONS}," == *",${key},"* ]]
}

ACTIVE_SPLIT_JSON_PATH="${DATA_SPLIT_JSON_PATH}"

run_one() {
  local run_name="$1"
  shift

  if ! contains_ablation "${run_name}"; then
    return 0
  fi

  local run_dir="${OUT_ROOT}/runs/${run_name}"
  local run_log="${OUT_ROOT}/logs/${run_name}.log"
  local cmd_file="${run_dir}/cmd.sh"
  mkdir -p "${run_dir}"

  local -a cmd=(
    python -m scripts.3d.train_3d_energy_distributed
    "${EXPERIMENT_NAME}"
    --trainer.output-folder "${run_dir}/train"
    --trainer.dataset-path "${DATASET_GLOB}"
    --trainer.dataset-group-pattern "${DATASET_GROUP_PATTERN}"
    --trainer.pkl-filter ""
    --trainer.no-use-sparse-dataset
    --trainer.no-use-full-coverage-sparse-dataset
    --trainer.train-on-potential-map
    --trainer.potential-map-loss smooth_l1
    --trainer.potential-map-smooth-l1-beta "${SMOOTH_L1_BETA}"
    --trainer.no-potential-map-use-atom-mask
    --trainer.patch-size "${PATCH_SIZE}"
    --energy-model.patch-size "${PATCH_SIZE}"
    --energy-model.reaction-field-mapping-version "${MAPPER_VERSION}"
    --energy-model.resnet-ngf "${RESNET_NGF}"
    --energy-model.resnet-n-blocks "${RESNET_N_BLOCKS}"
    --energy-model.resnet-dropout-p "${RESNET_DROPOUT_P}"
    --energy-model.resnet-padding-type "${RESNET_PADDING_TYPE}"
    --trainer.train-batch-size "${TRAIN_BATCH_SIZE}"
    --trainer.eval-batch-size "${EVAL_BATCH_SIZE}"
    --trainer.train-lr "${BASE_TRAIN_LR}"
    --trainer.final-train-lr "${BASE_FINAL_TRAIN_LR}"
    --trainer.train-num-steps "${BASE_TRAIN_STEPS}"
  )

  if [[ -n "${ACTIVE_SPLIT_JSON_PATH}" ]]; then
    cmd+=(--trainer.data-split-json-path "${ACTIVE_SPLIT_JSON_PATH}")
  fi

  if [[ "${RESNET_USE_DROPOUT}" == "true" ]]; then
    cmd+=(--energy-model.resnet-use-dropout)
  else
    cmd+=(--energy-model.no-resnet-use-dropout)
  fi

  if [[ "${USE_IONIC_CONC}" == "true" ]]; then
    cmd+=(--energy-model.use-ionic-conc)
  else
    cmd+=(--energy-model.no-use-ionic-conc)
  fi

  # Run-specific override(s): one factor changed per ablation.
  cmd+=("$@")

  {
    printf '%q ' "${cmd[@]}"
    printf '\n'
  } > "${cmd_file}"
  chmod +x "${cmd_file}"

  echo "=============================================="
  echo "Run: ${run_name}"
  echo "Log: ${run_log}"
  echo "Cmd: ${cmd_file}"
  echo "=============================================="

  CUDA_VISIBLE_DEVICES="${GPU_ID}" \
  WANDB_DISABLED="${WANDB_DISABLED}" \
  NNTOOL_OUTPUT_PATH="${NNTOOL_OUTPUT_PATH}" \
  NNTOOL_OUTPUT_PATH_DATE="${NNTOOL_OUTPUT_PATH_DATE}" \
    "${cmd[@]}" 2>&1 | tee "${run_log}"

  # Reuse the first generated split for all remaining runs if not explicitly provided.
  if [[ -z "${ACTIVE_SPLIT_JSON_PATH}" ]] && [[ "${AUTO_REUSE_SPLIT}" == "true" ]]; then
    local generated_split="${run_dir}/train/data_split.json"
    if [[ -f "${generated_split}" ]]; then
      ACTIVE_SPLIT_JSON_PATH="${generated_split}"
      echo "[INFO] Reusing generated split for following runs:"
      echo "       ${ACTIVE_SPLIT_JSON_PATH}"
    fi
  fi
}

# 6-run ablation suite
# 1) baseline
# 2) larger micro-batch
# 3) higher base LR
# 4) longer training
# 5) atom-mask supervised loss
# 6) denser random-crop atom threshold
run_one baseline
run_one batch4 --trainer.train-batch-size 4
run_one lr7e4 --trainer.train-lr 7e-4
run_one steps12k --trainer.train-num-steps 12000
run_one atommask --trainer.potential-map-use-atom-mask
run_one crop10 --trainer.random-crop-atom-num 10

echo "Ablation run set complete: ${OUT_ROOT}"
echo "Summarize with:"
echo "python -m scripts.3d.summarize_ablation_logs --run-set-dir ${OUT_ROOT}"
